# Generated by Django 4.1.13 on 2024-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafePick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productf',
            name='image',
            field=models.BinaryField(default=b''),
        ),
    ]
